### ISSUE TITLE
This response always false

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/galonku-backend#1]
I dont know why but response / result after compare the password and hash from database always false.

https://github.com/ariebrainware/galonku-backend/blob/928a1a940fd05a3357979a5d9a96e2088827a57b/api/merchant/controller/index.js#L108

@mhaidarh @michaeltamsil

**Comment by michaeltamsil** [comment]
* probably input have trailing spaces (try to remove trailing space using ``` trim()```) before hashing

**Comment by michaeltamsil** [comment]
* search "what best type to store bcrypt in mysql" (there's probably the issue)
mysql column type
mysql column length
mysql charset and collation

this is only guess (some my failure from the past)
